filter:
    excluded_paths:
        - 'docker/*'
        - 'public/*'
build:
    tests:
        override:
            -
                command: 'npm test'
                coverage:
                    file: 'coverage/clover.xml'
                    format: 'clover'
checks:
    javascript: true
build_failure_conditions:
    - 'issues.severity(>= MAJOR).new.exists'
    - 'project.metric("scrutinizer.quality", < 9)'
    - 'project.metric_change("scrutinizer.quality", < -0.10)'
    - 'project.metric("scrutinizer.test_coverage", < 0.80)'
    - 'project.metric_change("scrutinizer.test_coverage", < -0.10)'
