filter:
    excluded_paths:
        - 'docker/*'
        - 'public/*'
build:
    tests:
        override:
            -
                command: 'npm run lint'
                coverage:
                    file: 'coverage/clover.xml'
                    format: 'clover'
checks:
    javascript: true
build_failure_conditions:
    - 'issues.severity(>= CRITICAL).new.exists'
    - 'project.metric("scrutinizer.quality", < 9)'
    - 'project.metric_change("scrutinizer.quality", < -0.10)'
