language: node_js

node_js:
  - 8

cache:
  directories:
    - node_modules

services:
  - docker

branches:
  only:
    - master
    - develop
    - /^feature/*$/

addons:
  hosts:
    - carol-fr-dev.qarx.io
    - carol-co-uk-dev.qarx.io
    - carol-es-dev.qarx.io

env:
  global:
    - NODE_ENV=travis
    - BRANCH="${TRAVIS_PULL_REQUEST_BRANCH/\//-}"
    - BRANCH="${BRANCH,,}"
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
    - CLOUDSDK_CONTAINER_USE_CLIENT_CERTIFICATE=False
    - SELENIUM_BROWSER=chrome:59:LINUX
    - SELENIUM_REMOTE_URL=http://localhost:4444/wd/hub

before_install:
  - openssl aes-256-cbc -K $encrypted_490d653ff7a6_key -iv $encrypted_490d653ff7a6_iv -in credentials.tar.gz.enc -out credentials.tar.gz -d
  - tar -xzf credentials.tar.gz
  - export GOOGLE_APPLICATION_CREDENTIALS=quotatis-01d6e02592a9.json
  - scripts/run-selenium-standalone-chrome.sh

script:
  - if [ "${BRANCH}" = "" ]; then BRANCH=develop; fi;
  - if [[ "$TRAVIS_BRANCH" = "master" && $TRAVIS_PULL_REQUEST_BRANCH = "" ]]; then BRANCH=master; fi;
  - yarn run lint && yarn test
  - yarn build
  - yarn simulado:start &> simulado.log &
  - yarn simulado:prime &> simulado-prime.log &
  - yarn start &> server.log &
  - |
    while ! grep "Server listening" server.log; do
      echo "waiting for server to be listening…"
      sleep 1
    done
  - yarn cucumber
  - docker build -t eu.gcr.io/quotatis-152617/carol:${BRANCH} .

deploy:
  provider: script
  script: scripts/deploy.sh
  on:
    branch: develop

after_failure:
  - cat simulado.log
  - cat simulado-prime.log
  - cat server.log
