language: node_js

node_js:
  - "6.6.0"

cache:
  directories:
    - node_modules

install:
  - npm install

script:
  - mv src/config.js.dist src/config.js
  - npm run lint
  - npm run test:travis

branches:
  only:
  - master
  - develop
  - /^feature/*$/
