language: node_js

node_js:
  - 8

cache:
  directories:
    - node_modules

services:
  - docker

branches:
  only:
    - master
    - develop
    - /^feature/*$/

addons:
  hosts:
    - carol-fr-dev.qarx.io
    - carol-co-uk-dev.qarx.io
    - carol-es-dev.qarx.io

env:
  global:
    - NODE_ENV=mocks
    - BRANCH="${TRAVIS_PULL_REQUEST_BRANCH/\//-}"
    - BRANCH="${BRANCH,,}"
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
    - CLOUDSDK_CONTAINER_USE_CLIENT_CERTIFICATE=False
    - SELENIUM_BROWSER=chrome:59:LINUX
    - SELENIUM_REMOTE_URL=http://localhost:4444/wd/hub
    - GIT_SHA1=${TRAVIS_COMMIT}
    - DEV_SERVER=false

before_install:
  - openssl aes-256-cbc -K $encrypted_490d653ff7a6_key -iv $encrypted_490d653ff7a6_iv -in credentials.tar.gz.enc -out credentials.tar.gz -d
  - tar -xzf credentials.tar.gz
  - export GOOGLE_APPLICATION_CREDENTIALS=quotatis-01d6e02592a9.json
  - scripts/run-selenium-standalone-chrome.sh

script:
  - if [ "${BRANCH}" = "" ]; then BRANCH=develop; fi;
  - if [[ "$TRAVIS_BRANCH" = "master" && $TRAVIS_PULL_REQUEST_BRANCH = "" ]]; then BRANCH=develop; fi;

  - yarn lint
  - yarn lint:css
  - yarn test
  - yarn build
  - |
    travis_fold start server-and-simulado
      yarn start:mocks &>server-and-simulado.log &
      NEXT_WAIT_TIME=0
      until grep "Server listening" server-and-simulado.log || (( $NEXT_WAIT_TIME > 10 )); do
        echo "Waiting for server to be listening…"
        sleep $(( NEXT_WAIT_TIME++ ))
      done
    travis_fold end server-and-simulado
  - yarn cucumber -- --env travis

  - |
    if [[ $TRAVIS_BRANCH = "master" ]]; then
      travis_fold start deploy-to-qa
        docker build -t eu.gcr.io/quotatis-152617/carol:${BRANCH} .
        scripts/deploy.sh
      travis_fold end deploy-to-qa
      if [[ $TRAVIS_COMMIT_MESSAGE =~ ^v[0-9]+\.[0-9]+ ]]; then
        travis_fold start deploy-to-preprod
          yarn release:create
          ./scripts/deploy_carol_preprod.sh $TRAVIS_COMMIT_MESSAGE;
        travis_fold end deploy-to-preprod
      fi
    fi

after_failure:
  - cat server-and-simulado.log

