language: node_js

node_js:
  - 7

cache:
  directories:
    - node_modules

services:
  - docker

script:
  - if [ "${BRANCH}" = "" ]; then BRANCH=develop; fi;
  - yarn run lint && yarn test
  - docker build -t eu.gcr.io/quotatis-152617/carol:${BRANCH} .

branches:
  only:
    - master
    - develop
    - /^feature/*$/

after_success:
  - if [ "${BRANCH}" = "" ]; then BRANCH=develop; fi;
  - echo ${BRANCH}
  - curl https://sdk.cloud.google.com | bash
  - source /home/travis/.bashrc
  - gcloud components update kubectl
  - ./deploy-carol.sh

env:
  global:
    - BRANCH="${TRAVIS_PULL_REQUEST_BRANCH/\//-}"
    - BRANCH="${BRANCH,,}"
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
    - CLOUDSDK_CONTAINER_USE_CLIENT_CERTIFICATE=False

before_install:
  - openssl aes-256-cbc -K $encrypted_490d653ff7a6_key -iv $encrypted_490d653ff7a6_iv -in credentials.tar.gz.enc -out credentials.tar.gz -d
  - tar -xzf credentials.tar.gz
  - export GOOGLE_APPLICATION_CREDENTIALS=quotatis-01d6e02592a9.json
