export default {
  url: 'https://carol-co-uk-dev.qarx.io',
  proUrl: 'https://www.quotatispro.co.uk',
  contentUrl: 'http://api-service.qarx.io/uk/',
  countryLabel: 'country.great_britain',
  contentSiteUrl: 'https://www.quotatis.co.uk/advice/',
  footer: {
    advices: {
      window: 'guide/fenetres-portes-volets/fenetre/',
      shutter: 'guide/fenetres-portes-volets/volets/',
      roof_insulation: 'guide/isolation/isolation-des-combles/',
      wood_heating: 'guide/chauffage/chauffage-au-bois/',
      heat_pumps: 'guide/chauffage/pompe-a-chaleur/',
      solar_heating: 'guide/chauffage/le-chauffage-solaire/',
      heating_gas_oil: 'guide/chauffage/chauffage-gaz-fioul/',
      electric_heating: 'guide/chauffage/chauffage-electrique/',
      fireplaces: 'guide/chauffage/cheminee-poele/',
      heat_emitters: 'guide/chauffage/emetteurs-de-chaleur/',
      domestic_hot_water_production: 'guide/chauffage/production-deau-chaude-sanitaire/',
    },
    corporate: {
      contact: '/contact-form.html',
      about: 'qui-sommes-nous',
      job: '/emploi.html',
      use_conditions: 'cgu',
      guides: '',
      directory: '/annuaire-artisan',
      qpro: 'https://www.quotatispro.co.uk',
      adeo: 'http://www.adeo.com/',
      quote: '/travaux-entreprise.html',
      folder_projects: '/dossiers-travaux.html',
      trades: '/artisan-installateur-poseur-travaux.php',
    },
    social: {
      facebook: 'https://www.facebook.com/Quotatis.FR/',
      twitter: 'https://twitter.com/quotatisfr',
      linkedin: 'https://www.linkedin.com/company-beta/50071/',
      instagram: 'https://www.instagram.com/quotatis/',
    },
  },
}
