export const auth = {
  AUTH_TOKEN: 'AUTH_TOKEN',
  TOKEN_ERROR: 'TOKEN_ERROR',
  LOGIN_BAD_REQUEST: 'LOGIN_BAD_REQUEST',
  LOGIN_ERROR: 'LOGIN_ERROR'
}

export const user = {
  SIGNUP_SUCCESS: 'SIGNUP_SUCCESS',
  SIGNUP_ERROR: 'SIGNUP_ERROR',
  USER_INFO: 'USER_INFO',
  USER_UNAUTHORIZED: 'USER_UNAUTHORIZED',
  USER_UPDATE: 'USER_UPDATE',
  USER_ERROR: 'USER_ERROR'
}

export const content = {
  CONTENT_RECEIVE: 'CONTENT_RECEIVE',
  CONTENT_ERROR: 'CONTENT_ERROR'
}

export const pro = {
  PRO_LIST: 'PRO_LIST',
  PRO_LIST_FAIL: 'PRO_LIST_FAIL'
}
